# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.7
    - 3.6
    - 3.5

# specify what platforms of OS will be run
os:
  - linux
  #- osx
  #- windows

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda env create -f environment.yml
    - source activate CMIP6
    - conda install coverage
    - conda install coveralls
    - conda install pylint
    - conda install flake8
    - conda install pytest-cov


# a list of commands to run before the main script
before_script:
#

# the actual commands to run
script:
- pylint local_climate_change_tool/phase1_data_wrangler/test_data_wrangler.py

# generate a coverage report to send to back to user
after_success:
- coverage report
- coveralls
